from sqlalchemy import inspect, text
from sqlalchemy.engine import Engine


VERSION = "20260628_0002_import_batches_and_job_state"


def _add_column_if_missing(engine: Engine, table: str, column: str, ddl: str) -> None:
    inspector = inspect(engine)
    columns = {item["name"] for item in inspector.get_columns(table)}
    if column not in columns:
        with engine.begin() as connection:
            connection.execute(text(f"ALTER TABLE {table} ADD COLUMN {ddl}"))


def _create_index_if_missing(engine: Engine, index_name: str, ddl: str) -> None:
    inspector = inspect(engine)
    indexes = {item["name"] for item in inspector.get_indexes("import_jobs")}
    if index_name not in indexes:
        with engine.begin() as connection:
            connection.execute(text(ddl))


def upgrade(engine: Engine) -> None:
    batch_id_type = (
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if engine.dialect.name == "postgresql"
        else "INTEGER PRIMARY KEY"
    )
    with engine.begin() as connection:
        connection.execute(
            text(
                f"""
                CREATE TABLE IF NOT EXISTS import_batches (
                    id {batch_id_type},
                    source_type VARCHAR(50) DEFAULT 'PROGRESS_PDF',
                    status VARCHAR(30) DEFAULT 'QUEUED',
                    total_files INTEGER DEFAULT 0,
                    created_by VARCHAR(180),
                    summary TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    completed_at TIMESTAMP
                )
                """
            )
        )

    _add_column_if_missing(engine, "import_jobs", "source_identifier", "source_identifier VARCHAR(700)")
    _add_column_if_missing(engine, "import_jobs", "source_rev", "source_rev VARCHAR(120)")
    _add_column_if_missing(engine, "import_jobs", "source_fingerprint", "source_fingerprint VARCHAR(900)")
    _add_column_if_missing(engine, "import_jobs", "error_reason", "error_reason TEXT")
    _add_column_if_missing(engine, "import_jobs", "retry_count", "retry_count INTEGER DEFAULT 0")
    _add_column_if_missing(engine, "import_jobs", "max_retries", "max_retries INTEGER DEFAULT 2")

    _create_index_if_missing(
        engine,
        "ix_import_jobs_source_identifier",
        "CREATE INDEX ix_import_jobs_source_identifier ON import_jobs (source_identifier)",
    )
    _create_index_if_missing(
        engine,
        "ix_import_jobs_source_rev",
        "CREATE INDEX ix_import_jobs_source_rev ON import_jobs (source_rev)",
    )
    _create_index_if_missing(
        engine,
        "ix_import_jobs_source_fingerprint",
        "CREATE INDEX ix_import_jobs_source_fingerprint ON import_jobs (source_fingerprint)",
    )

    with engine.begin() as connection:
        connection.execute(text("UPDATE import_jobs SET retry_count = 0 WHERE retry_count IS NULL"))
        connection.execute(text("UPDATE import_jobs SET max_retries = 2 WHERE max_retries IS NULL"))
        legacy_batches = connection.execute(
            text(
                """
                SELECT COALESCE(batch_id, id) AS logical_batch_id,
                       COUNT(*) AS total_files,
                       MIN(created_at) AS created_at,
                       MAX(imported_by) AS created_by
                FROM import_jobs
                WHERE source_type = 'PROGRESS_PDF'
                GROUP BY COALESCE(batch_id, id)
                """
            )
        ).fetchall()

        for row in legacy_batches:
            connection.execute(
                text(
                    """
                    INSERT INTO import_batches (id, source_type, status, total_files, created_by, summary, created_at)
                    SELECT :id, 'PROGRESS_PDF', 'HISTORICAL', :total_files, :created_by,
                           'Batch historico creado por migracion de compatibilidad.', :created_at
                    WHERE NOT EXISTS (SELECT 1 FROM import_batches WHERE id = :id)
                    """
                ),
                {
                    "id": row.logical_batch_id,
                    "total_files": row.total_files,
                    "created_by": row.created_by,
                    "created_at": row.created_at,
                },
            )
            connection.execute(
                text(
                    """
                    UPDATE import_jobs
                    SET batch_id = :batch_id
                    WHERE source_type = 'PROGRESS_PDF'
                      AND COALESCE(batch_id, id) = :batch_id
                    """
                ),
                {"batch_id": row.logical_batch_id},
            )
